In [1]:
import itertools
import numpy as np

1) Вкладник поклав 50000 умовних одиниць на три різні рахунки в три різні банки. За першим рахунком виплати становитимуть 5% річних, по другому – 7% річних та по третьому 6% річних. Відомо, що через рік вкладник отримав за відсотками суму в 2250 у.о. з першого та другого банку та суму в 1400 у.о. з першого та третього банку. Скільки умовних одиниць він поклав на кожен рахунок спочатку?

In [2]:
A = np.array([[1, 1, 1],[0.05, 0.07, 0],[0.05, 0, 0.06]], dtype=float)
b = np.array([50000, 2250, 1400])

In [3]:
np.linalg.solve(A, b)

array([10000., 25000., 15000.])

2.На складі зберігаються мобільні телефони iPhone 6, iPhone 11, iPhone 12 моделей. Всього 1328 екземплярів. Моделей iPhone 6 на 120 менше, ніж моделей iPhone 11, та на 100 більше, ніж моделей iPhone 12. Скільки моделей кожного виду на складі?

In [4]:
A = np.array([[1, 1, 1], [-1, 1, 0], [1, 0, -1]], dtype=int)
b = np.array([1328, 120, 100], dtype=int)

In [5]:
np.linalg.solve(A, b)

array([436., 556., 336.])


3.Складіть канонічне рівняння еліпсоїда, що проходить через три точки A,B,C

In [6]:
A = np.array([np.sqrt(3), 0, np.sqrt(3)])
B = np.array([np.sqrt(6), 0.5, 0])
C = np.array([1, 1/(np.sqrt(3)), 1])

In [7]:
D = np.array([[A[0]**2, A[1]**2, A[2]**2], [B[0]**2, B[1]**2, B[2]**2], [C[0]**2, C[1]**2, C[2]**2]])
b = np.array([1, 1, 1])
res = np.linalg.solve(D, b)
a_2, b_2, c_2 = np.round(1/res)
a_2, b_2, c_2

(12.0, 1.0, 4.0)

In [8]:
a, b, c = np.round(1/np.sqrt(res), 5)
list(itertools.product((a, -a), (b, -b), (c, -c) ))

[(3.4641, 0.70711, 2.0),
 (3.4641, 0.70711, -2.0),
 (3.4641, -0.70711, 2.0),
 (3.4641, -0.70711, -2.0),
 (-3.4641, 0.70711, 2.0),
 (-3.4641, 0.70711, -2.0),
 (-3.4641, -0.70711, 2.0),
 (-3.4641, -0.70711, -2.0)]

4.Складіть рівняння параболи що проходить через задані три точки (1,12), (3,54), (-1,2). Необхідно знайти коефіцієнти рівняння a,b,c

In [9]:
A = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])
b = np.array([12, 54, 2])

In [10]:
np.linalg.solve(A, b)

array([4., 5., 3.])

5.Складіть функцію get_polynom, яка за набором точок виду(x1, y1), (x2, y2),... ,(xn+1, yn+1) буде знаходити коефіцієнти багаточлена ci. Таким чином функція приймає список кортежів з координатами та повертає набір коефіцієнтів c0, c1,..., cn.

In [91]:
def get_polynom(coords):
    a = np.empty((0,len(coords)), float)
    b = np.array([])
    for x, y in coords:
        b = np.append(b, y)
        a = np.append(a, [np.array([x ** val for val in range(0, len(coords))][::-1])], axis=0)
    print(a)
    print(b)
    return np.round(np.linalg.solve(a, b),3)

In [92]:
get_polynom([(-1,12), (3,54), (-1,2), (5, 4)])

[[ -1.   1.  -1.   1.]
 [ 27.   9.   3.   1.]
 [ -1.   1.  -1.   1.]
 [125.  25.   5.   1.]]
[12. 54.  2.  4.]


array([ 6.00479950e+15, -4.20335965e+16,  4.20335965e+16,  9.00719925e+16])